endpoints:
  - name: 'openai'
    url: 'https://api.openai.com/v1/'
    key: 'test-key-123'
    model: 'gpt-3.5-turbo'
  - name: 'mock-llm'
    url: 'http://localhost:8081/v1/'
    key: 'test-key'
    model: 'mock'
